import { Student, Contest, ContestParticipant } from "../types";

export const departments = [
  "Computer Science",
  "Information Technology",
  "Electronics",
  "Mechanical",
  "Civil",
];

export const classes = ["A", "B", "C", "D"];

export const years = [2021, 2022, 2023, 2024];

export const mockStudents: Student[] = [
  {
    id: "1",
    rollNo: "CS2021001",
    name: "Arjun Sharma",
    department: "Computer Science",
    class: "A",
    year: 2021,
    problemsSolved: { total: 245, easy: 120, medium: 95, hard: 30 },
    rating: 1850,
    globalRank: 15420,
    contestCount: 28,
    topPercent: 8.5,
  },
  {
    id: "2",
    rollNo: "IT2022015",
    name: "Priya Patel",
    department: "Information Technology",
    class: "B",
    year: 2022,
    problemsSolved: { total: 189, easy: 95, medium: 72, hard: 22 },
    rating: 1672,
    globalRank: 28340,
    contestCount: 22,
    topPercent: 12.3,
  },
  {
    id: "3",
    rollNo: "CS2023008",
    name: "Rahul Kumar",
    department: "Computer Science",
    class: "A",
    year: 2023,
    problemsSolved: { total: 312, easy: 145, medium: 128, hard: 39 },
    rating: 2045,
    globalRank: 8750,
    contestCount: 35,
    topPercent: 5.2,
  },
  {
    id: "4",
    rollNo: "EC2021025",
    name: "Sneha Reddy",
    department: "Electronics",
    class: "C",
    year: 2021,
    problemsSolved: { total: 156, easy: 88, medium: 55, hard: 13 },
    rating: 1523,
    globalRank: 45280,
    contestCount: 18,
    topPercent: 18.7,
  },
  {
    id: "5",
    rollNo: "IT2024003",
    name: "Vikram Singh",
    department: "Information Technology",
    class: "A",
    year: 2024,
    problemsSolved: { total: 98, easy: 65, medium: 28, hard: 5 },
    rating: 1324,
    globalRank: 72150,
    contestCount: 12,
    topPercent: 25.8,
  },
  {
    id: "6",
    rollNo: "CS2022017",
    name: "Ananya Joshi",
    department: "Computer Science",
    class: "B",
    year: 2022,
    problemsSolved: { total: 278, easy: 135, medium: 108, hard: 35 },
    rating: 1924,
    globalRank: 12680,
    contestCount: 31,
    topPercent: 6.8,
  },
];

export const mockContests: Contest[] = [
  {
    id: "1",
    title: "Weekly Contest 378",
    startTime: new Date("2024-01-15T10:30:00"),
    duration: 90,
    virtual: false,
    totalProblems: 4,
    participants: [
      {
        id: "1",
        rollNo: "CS2021001",
        name: "Arjun Sharma",
        problemsSolved: 3,
        totalProblems: 4,
        rating: 1850,
        rank: 245,
        trend: "up",
        finishTime: 4832,
      },
      {
        id: "3",
        rollNo: "CS2023008",
        name: "Rahul Kumar",
        problemsSolved: 4,
        totalProblems: 4,
        rating: 2045,
        rank: 128,
        trend: "up",
        finishTime: 5124,
      },
      {
        id: "6",
        rollNo: "CS2022017",
        name: "Ananya Joshi",
        problemsSolved: 3,
        totalProblems: 4,
        rating: 1924,
        rank: 198,
        trend: "down",
        finishTime: 4956,
      },
    ],
  },
  {
    id: "2",
    title: "Biweekly Contest 120",
    startTime: new Date("2024-01-20T20:00:00"),
    duration: 120,
    virtual: false,
    totalProblems: 4,
    participants: [
      {
        id: "1",
        rollNo: "CS2021001",
        name: "Arjun Sharma",
        problemsSolved: 2,
        totalProblems: 4,
        rating: 1850,
        rank: 1847,
        trend: "down",
        finishTime: 3245,
      },
      {
        id: "2",
        rollNo: "IT2022015",
        name: "Priya Patel",
        problemsSolved: 2,
        totalProblems: 4,
        rating: 1672,
        rank: 2156,
        trend: "up",
        finishTime: 4128,
      },
      {
        id: "4",
        rollNo: "EC2021025",
        name: "Sneha Reddy",
        problemsSolved: 1,
        totalProblems: 4,
        rating: 1523,
        rank: 3842,
        trend: "same",
        finishTime: 2891,
      },
    ],
  },
  {
    id: "3",
    title: "Virtual Contest - Dynamic Programming",
    startTime: new Date("2024-01-18T14:00:00"),
    duration: 180,
    virtual: true,
    totalProblems: 6,
    participants: [
      {
        id: "3",
        rollNo: "CS2023008",
        name: "Rahul Kumar",
        problemsSolved: 5,
        totalProblems: 6,
        rating: 2045,
        rank: 56,
        trend: "up",
        finishTime: 8964,
      },
      {
        id: "5",
        rollNo: "IT2024003",
        name: "Vikram Singh",
        problemsSolved: 2,
        totalProblems: 6,
        rating: 1324,
        rank: 1245,
        trend: "up",
        finishTime: 5234,
      },
      {
        id: "6",
        rollNo: "CS2022017",
        name: "Ananya Joshi",
        problemsSolved: 4,
        totalProblems: 6,
        rating: 1924,
        rank: 234,
        trend: "down",
        finishTime: 7832,
      },
    ],
  },
];

